### ISSUE TITLE
Evlas Ru site, does it have malware and paywalls?

### ISSUE THREAD

**Issue by Xevion** [VictiniX888/Illegal-Mod-Sites#105]
![image](https://user-images.githubusercontent.com/22359810/31344503-84d1f630-acd8-11e7-8b56-5961c0111212.png)
Evlas Ru site.
It's only marked with a paywall, but should it have malware?
Maybe it's a misunderstanding and it's blocking the paywall but just wondering.

**Comment by bilde2910** [comment]
evlas.ru seems to be down as of right now. I will keep it on the list as it seems that the domain owner has merely forgotten payment on the site, and it could go up again any time.

When this site was added to the list, we couldn't find evidence of malware, but it's quite possible that we missed something. When downloading a mod, we faced a paywall in order to proceed, which is why it's tagged like that on the list. Even though we can't access the site right now, I'll amend the list to state "potential malware" pending more extensive manual review.

Thanks for the suggestion!
