### ISSUE TITLE
9lifehack.com

### ISSUE THREAD

**Issue by MJRLegends** [VictiniX888/Illegal-Mod-Sites#106]
This site is reposting mod packs

http://9lifehack.com/

They are supplying link to download mods that are not official downloads, Also most of the mods are out of date versions and not working versions

**Comment by bilde2910** [comment]
Thank you for the submission! I sampled some mods from the site, but couldn't find any mods for which the site hosts files themselves. All of the mods and download links I tried ended up redirecting me to CurseForge for the download, and for the correct versions. Hence, unless specific examples are provided, I can't add this site to the list, because it seems to play by the rules. If you feel this is an incorrect evaluation, feel free to reopen this issue.

**Comment by MJRLegends** [comment]
@bilde2910 Ok an example would be http://9lifehack.com/extra-planets-mod-p39062 this is my mod and the downloads are hosted on curse and no mediafire links were ever public from my official download sources

**Comment by bilde2910** [comment]
Thank you for the example, and sorry for the belated response. The site has been added to the list along with the related site zinchat.com following review of your link.

Thanks for the suggestion! The sites should be blocked by StopModReposts within 5 minutes. A browser restart may also be required for the browser extensions to download the updated list from the StopModReposts servers. :-)

PS. You can send a DMCA takedown request to MediaFire to have them suspend the hosted file from their servers. Instructions are written on their [copyright page](http://www.mediafire.com/policy_violation/copyright.php). If you want to do this but you're not sure exactly how, there are DMCA templates that you can use where you can just fill in the relevant info.

**Comment by RyanLatour** [comment]
reposted my Minecraft map https://9lifehack.com/project-juryia-a-5k-by-5k-landscape-map.p500237
