### ISSUE TITLE
technicpack.net

### ISSUE THREAD

**Issue by MJRLegends** [VictiniX888/Illegal-Mod-Sites#108]
This site/launcher is full of stolen packs,

Many of my packs have been stolen and put on this site.

I have tried contacting them to remove them and they just ignore me messages and emails and just ban me from there discord for asking for 6 packs to be taken down as they are my packs

**Comment by bilde2910** [comment]
Technic Pack is a high-profile website. Adding this to the list will have very significant consequences for both us and Technic, so it will require very extensive research. I'll reach out to the Technic staff to ask for more info, and also ask around in various forums to try and get more info about the situation and Technic's reputation. I may also link Technic staff here. Know that the issue will be resolved fairly, but it might take some time to resolve. I'll keep all discussion on Technic in this issue.

Technic has been previously been discussed in #90. If the situation is as bad as you say, it definitely warrants further research. Flagging this as "on hold" while the situation is researched.

**Comment by bilde2910** [comment]
Also tagging @coolsquid and @VictiniX888 on this issue.

I also have to ask, for the record, you *did* try reporting the offending modpacks using the report button on their Technic pages?

**Comment by MJRLegends** [comment]
Yeah ive reported all of them many of times but they still seem to exist and seems like they get ignored as i see no changes or response.

**Comment by bilde2910** [comment]
I've been in touch with Technic staff about this issue and asked around for the proper procedure to report illegal modpacks. I also inquired about what happened to your reports. Here's what I've found so far.

The Technic staff member I talked to said that Technic's reporting system was "less than ideal" - generally, they apparently don't look at the queue because they do not have the required work force to do so. Everyone at Technic are too busy with other tasks to look at the reports. As a result, the queue keeps growing, and there are no responses to submitted reports. In my own opinion, that's a poor way of handling the issue. The staff member noted that the report system has to be redone for it to be usable by Technic staff, and that it's not being looked at for now.

I asked them what their preferred way of receiving reports was, and was in return sent a link to a form that you can use to submit such reports. You can fill in [this form](https://goo.gl/forms/6HDwjRCoFBNUl4yr2) to have your report considered by the staff. I was told that the responses to that form were checked often, so if you submit the offending modpacks there, they're likely to be removed somewhat quickly. As an alternative, they suggested you joining their Discord server and asking for help in #tech-help. That's a fast way to have the offending packs removed as well.

You mentioned that you were banned from that server for asking to have the packs removed. This seems to have been a misunderstanding. Asking for the packs to be removed on Discord is the recommended course of action, but the staff noted that you were banned for mention spam (i.e. tagging too many members, in this case, the staff, too much). The staff has unbanned you now, so you're free to rejoin their Discord server. They also removed one modpack that they could identify was stolen from you from the site. Just avoid mentioning the staff in your message. They, or a trusted member who can forward your inquiry to them, will see the message and get back to you.

I guess that sums up Technic's report handling process at this point. As for adding the site to the list; I will not be doing so at this time. The reason for this is that Technic has a procedure for reporting packs, by getting in touch over Discord, or filling out the form above. Furthermore, Technic's primary purpose is not to host stolen modpacks, but rather to host legitimate modpacks, and the existence of stolen modpacks in their directory is an unintended side effect of this purpose. Reports could admittedly be handled better, but at least to me, they have shown a willingness to take action against reported modpacks if they are informed that the existence of the modpacks on Technic is not authorized by the pack creators. Hence, there is no inherent malicious purpose behind the site, but the illegal modpacks are a side effect of low moderation capacity. That is of course not an excuse for hosting illegal content, so I will definitely follow the situation closely and see how the reports situation develops on Technic.

I will also add an issue to start drafting a help document on how to have content removed from various sites. This document will contain instructions on how to have content removed from Technic, as well as from other sites and third party domains.

**Comment by Pyker** [comment]
I would like to make one point extremely clear: We do **not** host modpacks. We merely store the modpack's URL (for example, Discord share link or other static file URL), or their Solder URL. Hosting the modpack is the user's responsability.

**Comment by MJRLegends** [comment]
Mod permissions really need to be looked at before they should be allowed to have downloads for it. This would solve all the current stealing issues that technic has a growing name for

**Comment by MJRLegends** [comment]
I've submitted all 7 reports of stolen packs of mine, using that google form link so hopefully it actually gets looked at,

@bilde2910 Thanks for your help. the banning on discord i dont agree with as the staff replied to most of my messages but didn't seem interested in the issue and just pasted it off as "yeah its a issue but we wont be fixing it anytime soon". After months of trying they annoyed me as i dont enjoy having work that I've spent over 2000 hours on stolen. It wouldn't of had to get to it if there was some visual feedback to the staff actually wanting to help the issue. From my site it feels like the staff are not even checking or doing anything Technic related. 

These are mostly the feels of every mod and mod pack dev, mod devs have even gone to the point in the past of making Technic launcher detectors and deleting/blocking their mods when used on Technic

**Comment by MJRLegends** [comment]
Also seems kinda wrong that they have a report feature on the site and a email address but both are ignored and the user isn't aware of this. Wouldn't it be better to supply this google form link? so people can actually get a report to the staff...

**Comment by bilde2910** [comment]
@Pyker Sorry about that, "hosting" was poor terminology on my part; it's more correct to say that you only reference the modpack files and have the Technic client download these files directly from a third party server. Hence you're not actually hosting the modpack files, but you provide easy access to these downloads by providing references to the download URLs, and it is the *list* of these URLs that you actually host and use directly in the launcher - not the files themselves.

@MJRLegends You're very welcome for the help. Hopefully the offending modpacks will be removed now that you have reported them through the form. I can't speak for how Technic staff work or operate as I haven't had much interaction with them. They do seem to be very busy from what I've personally heard.

If the staff don't have time to process the current reports queue, then I doubt they have the capacity to review mod permissions; it's a different order of magnitude when it comes to amount of work required. In an all perfect world, I would agree that this could have been nice, but at the current time, I personally am afraid it's not a realistic goal, and I guess it will never happen at all due to the required maintenance involved.

However, I do have some good news for you - I've talked with the staff, and they've confirmed that the report button on modpacks will be reworked; that it will be pointed to the form above, or one that is similar. I was not given a specific time frame for this, other than that it will happen "in the near future." This hopefully means that things are about to become better, and that modpack stealing on Technic will become less of an issue once this is implemented.

**Comment by GenPage** [comment]
@MJRLegends  Technic does not police mod permissions. We purposely have the report feature to allow the community to do so amongst themselves. The Technic Staff is comprised of volunteers, that as of late, has been very strained to the point of almost non-existent. Unforunately, the report feature was something that we were aware of, but the full extent was not fully apparent. 

@bilde2910 makes a great point with his 3rd paragraph. If we do not have the manpower to review modpack after the fact, no one would be able to make packs if we had to hand verify them upfront prior to allowing them to be downloaded.

My task as of late has been to rebuild the staff team. Originally this did not include moderators, but it does now. We have made significant progress as we are now able to take on tasks that originally wouldn't consider. It will be slow going, but hopefully the degradation of features that Technic Platform will be halted and reversed. All that I ask that the community is patient and understanding with the staff as we progress. Constructive feedback is welcome, but please only as long as it is constructive. It's not going to be easy going as shown here but together we can get there.

**Comment by MJRLegends** [comment]
@GenPage I appreciate that but shouldn't pack submitting be stopped if Technic doesn't have the staff to see the reports coming in. Seems kinda wrong to trade off the Technic staff not having time as just letting people steal mod and mod packs devs very hard work and time that they have spent and then gets degraded from seeing their packs gets downloads on Technic and knowing they cant do much about it.

Hopefully it can be improved, lets just hope its not already to late and Technic has grown to much of a name over the stolen packs issue.

**Comment by GenPage** [comment]
@MJRLegends stopping pack submitting is not an option. Mind as well shut the site down completely right then instead. Instead I suggest more community involvement, especially in our Discord server to help assist our current and future staff in combating this. The biggest issue we see is trying to determine valid vs invalid reports.

**Comment by MJRLegends** [comment]
@GenPage i will be prepared to send you a list of urls that are all stolen versions. all the FTB ones are 100% non Technic so thats a easy place to start.

**Comment by MJRLegends** [comment]
The community (including myself) is just looking for a active way to report packs and get a visual response pack that its been seen by the staff. As its taken many of trips to the discord over the past years and many of emails and reports using the current report feature and only when i posted it here is when i finally seen some visual response.

**Comment by coolsquid** [comment]
I am a bit late to the show, but I would like to share my thoughts nonetheless:

When I initially created this list, my primary targets were sites like 9minecraft, which monetize the work of others and put users at risk, with minimal effort of their own. Technic is not such a site. While it does have some problems with unauthorized distribution, the platform itself is ad-free and of high quality, and has received much effort from its creators. I do not believe that some minor moderation issues on an otherwise decent site should lead to inclusion on the list.

Furthermore, adding Technic to the list without highly convincing arguments would be undesirable from a pragmatic point of view, as it would seriously damage the credibility of the list. Therefore, the arguments in favor of inclusion would have to be particularly convincing for me to support it.
