### ISSUE TITLE
Add the extension "www" to the hosts file (and plain text)

### ISSUE THREAD

**Issue by unixfox** [VictiniX888/Illegal-Mod-Sites#125]
Some illegal websites serve their website on www.domain.com instead of domain.com. For example 9minecraft.net does that (http://www.9minecraft.net/) and it doesn't get blocked by my software who use the [hosts file](https://github.com/VictiniX888/Illegal-Mod-Sites/wiki/API-access-and-formats#hosts-file-hoststxt) ([PiHole](https://pi-hole.net/)) because it's listed `9minecraft.net` not `www.9minecraft.net`.

Is it possible to add the extension `www` to every domains listed on the hosts file (and plain text)?

**Comment by bilde2910** [comment]
That's a good point. I've updated the hosts file script to output the domain list prepended with `www.` for each domain in addition to the top level domains themselves. You should be able to refresh the hosts file in pi-hole now to get all the sites with the `www.` included, so that they're blocked on your network.
