### ISSUE TITLE
Unapproved SilkSpawners forge edition mod Website

### ISSUE THREAD

**Issue by jredfox** [VictiniX888/Illegal-Mod-Sites#126]
I approve of 9minecraft.net minecraftmods.com and curseforge/mc forums for forks/modifications(if credit given to source) , and the official links. I have three issues with this a: malwere site, b: they are stealing downloads, c: they hosted my file on their website on an unapproved site via my eula's permissions 
**My mod**: https://minecraft.curseforge.com/projects/silk-spawners-forge-edition

FAKE1: http://www.minecrafteo.com/silk-spawners-mod-para-minecraft-1-12/
Fake2: http://minecraftmodpacks.net/mods/silk-spawners-forge-edition/
Fake3: https://www.comoinstalarmodsminecraft.com.br/2018/02/como-instalar-silk-spawners-mod-1122.html
Fake4:http://zonacraft.net/silk-spawners-mod/
Fake5:https://minecraftdownloadaz.blogspot.com/2018/02/silk-spawners-forge-edition-mods.html

**Comment by jredfox** [comment]
this github is a fake I don't see any results taken by reports and the freaken mod repost website link took me to another github

**Comment by bilde2910** [comment]
Hi jredfox,

Adding sites to the list is a more extensive process than it might look like. For each site, we have to visit the site, look for ads, look for redistribution of mod files (usually several different mods on the site), verifying the licenses of mods that are hosted there, fact-checking the contents, etc. This is a process that takes a little time, and we don't always have the time or motivation to do it every time a ticket comes in. I am the only active collaborator in this project right now, and I usually wait for a few days or wait for a few more reports before I start researching several sites in one batch. It's not my job to look into the sites; I do studies and other things next to this project, so I don't always have time. Don't expect us to look at a ticket the same day it's posted. It usually takes a few days before I find time to take a look.

The website links to the repository of MMPL (as far as I can recall). I should see if I could get this changed, but I don't know off the top of my head which of the collaborators is responsible for hosting the site, and they aren't usually too active in this repo. I've noted it, though.

With that said, I've looked at the sites you reported:

- minecrafteo dot com does not seem to spread misinformation or host any advertising, and download links point to CurseForge, so we won't add the site right now.
- minecraftmodpacks dot net is already on the list for misleading users about its contents. Your mod files are not hosted here at all as far as I can see, but again, it's already listed due to other reasons.
- comoinstalarmodsminecraft dot com dot br is also already listed for being misleading and advertising, but not currently for redistribution. Download links point to CurseForge.
- zonacraft dot net is definitely redistributing mods, so we've added it to the list per your report.
- minecraftdownloadaz dot blogspot dot com is also already listed for redistribution.

Thank you for your submission!

**Comment by jredfox** [comment]
no I am the copyright owner and if they host a file that isn't theirs or the site contains malwere it's against my eula and they can't have it there. It's against the law. I filed google complaints they will be taken them down as for you your a fraud

**Comment by bilde2910** [comment]
Hi jredfox,

The sites that we did not add, were not added because they do not host the files. The two last sites (zonacraft and minecraftdownloadaz) are both already listed and known for redistribution. These sites host files on servers and locations that you have not approved, and their ratings reflect that.

The first three, however, do not host the files. Please take a look for yourself for minecrafteo:

![minecrafteo](https://user-images.githubusercontent.com/6617815/36301371-d9a6a8b2-1304-11e8-9251-352776788b9a.png)

For comoinstalarmodsminecraft:

![comoinstalarmodsminecraft](https://user-images.githubusercontent.com/6617815/36301384-e5a6a39c-1304-11e8-937e-6d0be76dd417.png)

And finally for minecraftmodpacks, they don't seem to have any download links at all:

![minecraftmodpacks](https://user-images.githubusercontent.com/6617815/36301480-47e5ffb2-1305-11e8-9ec5-b8740b89311a.png)

None of the sites here are known to host malware, and we cannot put forth claims that they do host malware without proof that can support such a statement. Further, since they do not host files as far as we can see, we cannot add it to the list. If you have proof otherwise, please let us know, and we'll do another review with your proof in mind. The fact that they have a download link does not necessarily mean that they are the ones hosting it.

Also note that talking about and making articles about a mod is not in any way illegal, and can be freely done as long as they do not use copyrighted materials (images, text, files etc.) and while they are not under an agreement (NDA) that prevents them from talking about the mod. If they *are* using copyrighted material specifically without permission, you can try sending a DMCA takedown request for using infringing content.

**Comment by jredfox** [comment]
yeah one of them I found out wasn't a file host but, the rest of them are hosting my files with dl links to their sites you can remove that one off your list

**Comment by bilde2910** [comment]
I've been a bit busy, so I didn't have time to come back before now, sorry.

The links on their sites *do* point to CurseForge, as indicated in my previous reply. Feel free to prove otherwise if you feel that I am mistaken.

Also, I am not questioning your ownership of the files. You definitely own them. I am just saying that *talking/writing* about them is not illegal, as long as they are not re-uploading your files, which they do not seem to be doing. We can also not find any malware on the site at this time.

**Comment by jredfox** [comment]
I don't care whether or not they link back to the original mod I am the copy right owner and I say whether or not it's safe for users. They have adds saying dl now and it's their and or virus files from their site and or other sites

**Comment by bilde2910** [comment]
The point is that these sites link back to *your original, approved hosting site*. As copyright owner, you do not get the right to prevent people from talking about or making articles etc. about your mod, or to deny websites the right to create such articles. You *do* have the right to issue takedowns to the site or its host if they are redistributing something you've made, which they currently are not doing.

Please verify for yourself that the files are not hosted on these sites. You have repeatedly claimed that the two sites are hosting your files, but have not provided proof of this. Please prove this, and we will add the sites to the list.

Disclaimer: I am not a lawyer, by the way.
