### ISSUE TITLE
Zonacraft updates

### ISSUE THREAD

**Issue by JayZX535** [VictiniX888/Illegal-Mod-Sites#129]
Spoke with Zonacraft recently, they said they are working on an update to automatically use official links for their software.  Might be worth keeping an eye on them in that case-- they seemed compliant enough when I raised concerns about them having reposted my mod.
They didn't use my adfly links but they seem to be pulling mod descriptions off the Curseforge site,s where adfly isn't fully applicable.
With that said the update does not appear to be in effect at the time that I'm posting this, so we'll see if they do in fact implement it or not...

**Comment by bilde2910** [comment]
Zonacraft still uses unofficial file hosts. For that reason, I won't be removing the site now, though if they do change everything to only use official links, then removal can be considered. While they might be compliant with requests to remove unofficial download links, the problem is that it has those links in the first place. We'll see what happens if they add in this update.
