### ISSUE TITLE
Skydaz website

### ISSUE THREAD

**Issue by Mwthorn** [VictiniX888/Illegal-Mod-Sites#35]
https://www.skydaz.com

Searching for a mod called "Helpful Villagers" I found it on this website as well.
I believe this website might be another repost of mods. Their links seems to guide to their own download links. (not 100% sure, didn't want to click the download links)
However, they do credit the actual modder and provide a link to the original thread but that doesn't really make any difference to me, still seems illegal. You agree or am I mistaken?

Sources:
https://www.skydaz.com/helpful-villagers-mod-installer-for-minecraft-1-7-10/
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2162777-helpful-villagers-v1-2-0-new-update-villager

**Comment by VictiniX888** [comment]
Ah, good old Skydaz.
We actually had a really big discussion somewhere about this, and in the end we came to the conclusion that it is not reposting mods, and thus not doing anything illegal.
Thanks for contributing though ;)

**Comment by Mwthorn** [comment]
Oh, sorry bout dublication issues :3

**Comment by Pyker** [comment]
Hello. I think this issue should be re-opened and Skydaz should be added to the list, as it is rehosting mods at https://www.skyworxz.com/. The installer mentioned in the first post, as an example, downloads from there:
```c#
this.mod_download = "http://www.skyworxz.com/mods/1.7.10/HelpfulVillagers1.7.10.zip";
```

**Comment by bilde2910** [comment]
Hi Pyker,

I unfortunately don't have time to review it right now, but I'll re-open the issue and take a look at it as soon as I have time. I'll be on a train tomorrow for a few hours, so I'll likely get back to it then. Thanks for raising these concerns.

We did not add it back in 2015 based on a lengthy discussion about it (I don't remember exactly where it was; probably either the forums or IRC), but if they've changed course since then, a new review is definitely warranted.

**Comment by bilde2910** [comment]
I reached out to some devs to verify distribution rights and checked the licenses for a few mods they provide installers for. We put forth a requirement back in 2015 that the site collects permission from mods they post on the site. This would include either a compatible license on the mod (e.g. GPL, MIT, Apache), or an explicit agreement by the owner of the mod. Many of the mods hosted on the site satisfy the license requirement, but not all do, and it seems that at least a few of them do not have explicit permissions from the mod author.

Skydaz was a special case because it allowed an easy way to install mods. However, installing mods has only gotten easier, with new launchers, centralized hosting (CurseForge) and better technical implementations. So the days of Skydaz are numbered. Skydaz also hosts out-of-date versions of many mods, and while they credit authors, they do not apparently collect permission from modders. For these reasons, I will add Skydaz to the list.

Thanks for the report.

**Comment by Pyker** [comment]
Thank you for your quick response 👍
