### ISSUE TITLE
Consider adding sites that bait people by reporting false info

### ISSUE THREAD

**Issue by cheatfreak47** [VictiniX888/Illegal-Mod-Sites#88]
One thing I've noticed is some sites pull stuff like this just to get clicks and prey on search engine users.
These sites, while often linking to the original site, are making money off of ads and, in this example, the mod it lists for "Minecraft 1.12/1.11" hasn't been updated to support 1.11.

This behaviour is dishonest, and not only that but they shamelessly admit that is the case, after they have you on their page, and viewing whatever ad they wanted and have their pennies.

![chrome_2017-03-02_00-12-44](https://cloud.githubusercontent.com/assets/7818664/23493938/7a937ca6-fedd-11e6-9aba-a238f11e1d90.png)

specifically this is on http://modsmc.com/

**Comment by bilde2910** [comment]
Hi, @cheatfreak47! I've looked through the list and there seems to be precedence for adding lists that don't redistribute the mods but which are heavy on ads and misleading information. The problem with these sites is that downloaders go there, thinking that a mod is updated, and when they find that it isn't, they go and complain to the mod author. So while the mod is downloaded from the original source, it loses reputation because of something that is out of control of the modder.

I'll review the site and see if it qualifies for the list since this is clearly deceptive behavior. Thanks for reporting the site.

**Comment by bilde2910** [comment]
I've taken a look at the site. It doesn't appear to have any advertisements, hence it would be rated:

Advertising: 1  
Redistribution: 1  
Miscellaneous: 5

The precedence for sites of this rating is much weaker. There are only two sites on the list that I could immediately spot with that rating; one got the score because it solely offers malware and the other no longer offers working download links, so I cannot reevaluate it. I'd say it is deceptive and I'd add it to the list, but I'd need to have the input of @coolsquid or @VictiniX888 before adding it to the list.

I picked [this mod on the site](http://modsmc.com/mo-creatures-mod/) as an example of deception. It claims 1.12/1.11.2 downloads for a mod that is only updated to 1.10.2. (Note, 1.12 doesn't even exist.) Awaiting input of other collaborators.

**Comment by VictiniX888** [comment]
I'm all for adding it to the list, as the site is built on deception. There are several other sites on the list that are added due to misleading information, so even though this one doesn't have any ads it should still be accepted.
